version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: Task_Manager_Client1205 # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port mapping
 
 express: # name of the second service
  build: TaskManager # specify the directory of the Dockerfile
  ports:
  - "3636:3636" #specify ports mapping
  links:
  - mongo # link this service to the database service
 
 mongo: # name of the third service
  image: mongo:latest # specify image to build container from
  volumes:
  - ./data:/data/db
  command: --smallfiles
  ports:
  - "27017:27017" # specify port forwarding